### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by houjingyi233** [sslab-gatech/janus#1]
./compile -t btrfs -c
scripts/Makefile.clean:15: drivers/input/Makefile: No such file or directory
make[2]: *** No rule to make target 'drivers/input/Makefile'.  Stop.
make[1]: *** [scripts/Makefile.clean:89: drivers/input] Error 2
make: *** [Makefile:1300: _clean_drivers] Error 2
Traceback (most recent call last):
  File "./compile", line 24, in <module>
    subprocess.check_call('make clean', shell=True)
  File "/usr/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'make clean' returned non-zero exit status 2

compare with https://github.com/lkl/linux, I noticed that https://github.com/sslab-gatech/janus/tree/master/lkl missing gnss and input directory, so what's the problem?

**Comment by tarafans** [comment]
Missed files because of wrong gitignore
