### ISSUE TITLE
Error while seeding images

### ISSUE THREAD

**Issue by TejasDuseja** [sslab-gatech/janus#4]
While mounting ext4 image using sudo ./istat -i ../samples/evaluation/ext4-00.image -t ext4 -o ext4.istat command
I am getting error 
tmp image: /tmp/tmpCELc3L
mount dir: /tmp/tmp6jexwh
['sudo', 'mount', '-o', 'loop', '-t', 'ext4', '/tmp/tmpCELc3L', '/tmp/tmp6jexwh']
mount: wrong fs type, bad option, bad superblock on /dev/loop0,
       missing codepage or helper program, or other error

       In some cases useful info is found in syslog - try
       dmesg | tail or so.
Traceback (most recent call last):
  File "./istat", line 130, in <module>
    mount(args.type, tmp_img_path, mnt_dir)
  File "./istat", line 23, in mount
    ['sudo', 'mount', '-o', ','.join(['loop'] + options), '-t', fstype, path, mntpoint])
  File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['sudo', 'mount', '-o', 'loop', '-t', 'ext4', '/tmp/tmpCELc3L', '/tmp/tmp6jexwh']' returned non-zero exit status 32
Can anyone help me figuring out what went wrong?

**Comment by tarafans** [comment]
Could you please show the result of `file ../samples/evaluation/ext4-00.image` and `md5sum ../samples/evaluation/ext4-00.image`?

**Comment by wulasite** [comment]
> Could you please show the result of `file ../samples/evaluation/ext4-00.image` and `md5sum ../samples/evaluation/ext4-00.image`?

I meet the same problem when i run ./istat -i ../samples/evaluation/btrfs-00.image -t btrfs -o btrfs.istat

# file ../samples/evaluation/btrfs-00.image 
../samples/evaluation/btrfs-00.image: ASCII text
# md5sum ../samples/evaluation/btrfs-00.image 
0151dd1e106b623f874b5bfd752e9945  ../samples/evaluation/btrfs-00.image

**Comment by tarafans** [comment]
../samples/evaluation/btrfs-00.image is not an image but a LFS description file I guess.
We are limited on using LFS. Instead, I upload samples.zip which include the starting images.

**Comment by wulasite** [comment]
It works! Thanks!
