### ISSUE TITLE
Error while Compile (ported) lkl 4.17

### ISSUE THREAD

**Issue by wulasite** [sslab-gatech/janus#5]
when I run ./compile -t btrfs -c in lkl, i get some error msg:

afl-llvm-pass 2.52b by <lszekeres@google.com>
[+] Instrumented 62 locations (non-hardened mode, ratio 100%).
afl-llvm-pass 2.52b by <lszekeres@google.com>
[+] Instrumented 68 locations (non-hardened mode, ratio 100%).
  AR      fs/kernfs/built-in.a
  AR      drivers/char/hw_random/built-in.a
  AR      drivers/hwmon/built-in.a
  AR      kernel/time/built-in.a
afl-llvm-pass 2.52b by <lszekeres@google.com>
[+] Instrumented 61 locations (non-hardened mode, ratio 100%).
clang-6.0: error: unable to execute command: Segmentation fault (core dumped)
clang-6.0: error: clang frontend command failed due to signal (use -v to see invocation)
clang version 6.0.0 (tags/RELEASE_600/final)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /opt/clang+llvm-6.0.0-x86_64-linux-gnu-ubuntu-16.04/bin
clang-6.0: note: diagnostic msg: PLEASE submit a bug report to http://llvm.org/bugs/ and include the crash backtrace, preprocessed source, and associated run script.
clang-6.0: warning: optimization flag '-fmerge-constants' is not supported [-Wignored-optimization-argument]
clang-6.0: error: unable to execute command: Segmentation fault (core dumped)
clang-6.0: error: clang frontend command failed due to signal (use -v to see invocation)
clang version 6.0.0 (tags/RELEASE_600/final)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /opt/clang+llvm-6.0.0-x86_64-linux-gnu-ubuntu-16.04/bin
clang-6.0: note: diagnostic msg: PLEASE submit a bug report to http://llvm.org/bugs/ and include the crash backtrace, preprocessed source, and associated run script.
clang-6.0: warning: optimization flag '-fmerge-constants' is not supported [-Wignored-optimization-argument]
clang-6.0: error: unable to execute command: Segmentation fault (core dumped)
clang-6.0: error: clang frontend command failed due to signal (use -v to see invocation)
clang version 6.0.0 (tags/RELEASE_600/final)
Target: x86_64-unknown-linux-gnu

I can't find out why.

**Comment by wulasite** [comment]
My OS：Linux ubuntu 4.15.0-45-generic #48~16.04.1-Ubuntu SMP Tue Jan 29 18:03:48 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
clang: clang version 6.0.0 (tags/RELEASE_600/final)
gcc: gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.12)

**Comment by TejasDuseja** [comment]
I ran into same error msg a while ago. The source of the problem that i found was that i was installing llvm and clang by running sudo apt-get install clang && llvm. Basically these commands was shipping me old version of llvm i.e llvm 3.0 . To resolve the problem I build clang 6.0.0 with llvm 6.0.0 from source.

**Comment by wulasite** [comment]
> I ran into same error msg a while ago. The source of the problem that i found was that i was installing llvm and clang by running sudo apt-get install clang && llvm. Basically these commands was shipping me old version of llvm i.e llvm 3.0 . To resolve the problem I build clang 6.0.0 with llvm 6.0.0 from source.

Thanks!I will try!

**Comment by wulasite** [comment]
Thanks! It works for me!
